### ISSUE TITLE
Emote menu is borked, thanks to Twitch

### ISSUE THREAD

**Issue by thinkpad4** [cletusc/Userscript--Twitch-Chat-Emotes#101]
Use the user-emotes service in all places since tmiSession's emote parser has been removed.  there is no longer a function in the session controller called getEmotes

**Comment by Nareese** [comment]
FYI the specific issue is session.getEmotes() is not a function at https://github.com/cletusc/Userscript--Twitch-Chat-Emotes/blob/master/src/modules/twitch-api.js#L93

**Comment by cletusc** [comment]
Got any docs on the "user-emotes" service? tmiSession has always been unstable.

**Comment by Nareese** [comment]
Possibly https://dev.twitch.tv/docs/v5/reference/chat/#get-chat-emoticons-by-set et al?  I don't actually have any idea if that's the intended replacement or if there's something else.  There's absolutely no discussion of the removal of this functionality on the dev tmi/chat or api boards.  It may be worth posting a question there and asking.

**Comment by night** [comment]
@cletusc if you can setup travis to build and release this it would make it easier for me to maintain.. im not able to build this locally, some deps are screwy. i will fix this in my fork in a few

**Comment by cletusc** [comment]
My main concern is getting it working as-is with my current dev setup, then I'll look into setting up travis. I've got a method working for the actual retrieval of emotes (that's probably more reliable as it's an actual API call); however, there are some sorting issues popping up that I need to fix.

This won't be fixed until probably tomorrow night or some time this weekend as I don't currently have a whole lot of free time to work on this.

**Comment by night** [comment]
im gonna hotfix it for the moment in my fork then, if you have time i'd love to work with you on getting this better maintainable :)

**Comment by cletusc** [comment]
Sorry for the delay on this. This is fixed by 1415ae5a3b6dd47f70926a5213fab078b068b1e4. [v2.1.5](https://github.com/cletusc/Userscript--Twitch-Chat-Emotes/releases/tag/v2.1.5) is released.
