### ISSUE TITLE
No bttv emtoes

### ISSUE THREAD

**Issue by Marcin44** [cletusc/Userscript--Twitch-Chat-Emotes#102]
There is no bttv emotes under button, but yesterday there were these emoticons.

**Comment by cletusc** [comment]
Unfortunately it's not something I can do to fix--this is a BTTV issue if it's affecting more than you. The API for adding emotes to the emote menu haven't changed.

@Night I'll let you handle this one.

**Comment by night** [comment]
They work for me.. possible they failed to load them from the API so they weren't loaded in BetterTTV at all.

**Comment by cletusc** [comment]
Fair enough--closing this.

@Marcin44 you can trying clearing cache and reloading to see if it helps. Other than that, can't really help--sorry!
