### ISSUE TITLE
Re-enable middle-mouse compass scrolling on menu

### ISSUE THREAD

**Issue by cletusc** [cletusc/Userscript--Twitch-Chat-Emotes#76]
From http://cletusc.github.io/Userscript--Twitch-Chat-Emotes/#comment-1895391020

> Feature Request: Please add center mouse click scrolling. My emote menu is very large and can be painful to scroll through.

This is related to https://github.com/mzubala/jquery-custom-scrollbar but I don't know how feasible this is to fix--marking low priority right now as I don't think this affects more than a small amount of users that are subbed to an obscene amount of people.

**Comment by Izlsnizzt** [comment]
[Teak](https://github.com/teak) Suggested: Bind the mouse down event and use the scrolling API to change the scroll location.

**Comment by cletusc** [comment]
The problem with doing it that way is not all OSes bring up the scroll compass when middle clicking and instead try to paste.

**Comment by cletusc** [comment]
@Izlsnizzt, I will likely be switching to [gromo/jquery.scrollbar](https://github.com/gromo/jquery.scrollbar) instead of [mzubala/jquery-custom-scrollbar](https://github.com/mzubala/jquery-custom-scrollbar) as it actually supports this [based on their demos](http://gromo.github.io/jquery.scrollbar/demo/basic.html).

It doesn't emulate scrolling like most plugins out there, it just hides the native scrollbar in favor of a custom one so all default scrolling behavior should persist. The only issue I see is that the custom scroll bar wouldn't be shown on non-webkit browsers on Mac, but I don't think it'd be too terrible.
