### ISSUE TITLE
:/ Monkey emote appears in "Turbo" section

### ISSUE THREAD

**Issue by cletusc** [cletusc/Userscript--Twitch-Chat-Emotes#78]
![](https://a.pomf.se/olszfx.png)

**Comment by Overhunter1** [comment]
Well i believe the issue is for the :/ emote is that its missing its command promt like when i click on the icon it only puts up : and not the entire emote but yea i think thats pretty much the problem cause of the turbo monkey one.

**Comment by cletusc** [comment]
The parsing of the `:/` emote is fixed by 5715d9fbd84002e38b1c9dea338f74d9f22890a6 but I am still working on the sorting.

**Comment by cletusc** [comment]
Closing this as it is now intended behavior. All turbo emotes will go in the Turbo group, this includes the monkey emotes, bubble emotes, and the "hidden" turbo emote (`KappaHD` and others).

This was changed by 7dcbdf5522287327b4caafb7a4759815ef006f21
