### ISSUE TITLE
Basic Emotes adding a ^ and a $

### ISSUE THREAD

**Issue by gapotter** [cletusc/Userscript--Twitch-Chat-Emotes#80]
Hello - for some reason, the first / most basic e-motes are adding a ^ and a $ to the simple emotes

For example:  The simple Heart, which is <3 is displaying ^<3$ 

The Happy face, which is :) is sending ^:)$  to the chat box.

Please fix !!  Thanks ^:p$

**Comment by cletusc** [comment]
Fixed by 8641b600555e5262c4dfad6f7be05b9bf8920b2f but I haven't merged it into the stable branch yet as there are still some issues pending. Leaving this open until it gets merged.

**Comment by gapotter** [comment]
K thanks!
