### ISSUE TITLE
BTTV emotes not appearing

### ISSUE THREAD

**Issue by Cheezilla** [cletusc/Userscript--Twitch-Chat-Emotes#96]
I have a paid subscription to BTTV emotes. Lately my emotes and all bttv emotes are missing form the emote menu. When I cope paste them in the still appear but I cannot easily access them

**Comment by cletusc** [comment]
Unfortunately, this isn't something I can fix on my end. The integration still works the way it has for months (just tested), so if it just recently broke, that is likely on the BTTV end. Paging @night
